### ISSUE TITLE
仓库内容已上传至“交大門”网站https://xjtu.men/c/survive/12

### ISSUE THREAD

**Issue by xjtumen** [Survive-XJTU-CS/SurviveXJTUCS#8]
您好，为了便利信息的传播，考虑到学校里面会用git的人不多，国内到Github的网络经常抽风，我们已经将您的这个仓库的内容搬到["交大門"网站](https://xjtu.men)的[西安交大CS生存指南类别](https://xjtu.men/c/survive/12) 来。
内容可以在线编辑，普通用户可以通过回复便捷地添加内容，即使后面想要把内容整理到其他平台，可以调用API或者PG数据库导出。
"交大門"网站为完全非商业且以用户体验为重的交大人的自由交流平台。

**Comment by siyuanluo** [comment]
好的，只要不商用就可以。
